/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ylcq_ndkgif_GifHandler */

#ifndef _Included_com_ylcq_ndkgif_GifHandler
#define _Included_com_ylcq_ndkgif_GifHandler
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ylcq_ndkgif_GifHandler
 * Method:    loadGif
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_ylcq_ndkgif_GifHandler_loadGif
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_ylcq_ndkgif_GifHandler
 * Method:    getWidth
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_ylcq_ndkgif_GifHandler_getWidth
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_ylcq_ndkgif_GifHandler
 * Method:    getHeight
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_ylcq_ndkgif_GifHandler_getHeight
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_ylcq_ndkgif_GifHandler
 * Method:    getNextTime
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_ylcq_ndkgif_GifHandler_getNextTime
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_ylcq_ndkgif_GifHandler
 * Method:    updateFrame
 * Signature: (JLandroid/graphics/Bitmap;)I
 */
JNIEXPORT jint JNICALL Java_com_ylcq_ndkgif_GifHandler_updateFrame
  (JNIEnv *, jclass, jlong, jobject);

#ifdef __cplusplus
}
#endif
#endif
